Travis configuration

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -3,7 +3,9 @@ sudo: false
 
 env:
   global:
-    # Doctr deploy key for NSLS-II/PyXRF
+    - SUBMIT_CODECOV: false
+    - BUILD_DOCS: false
+    - GH_REF: github.com/NSLS-II/PyXRF.git
     - secure: "ZYRymELlWT6UQNEU4M57jEWfHGy+e04OBEqbhzLiJMc1LBAOKyBlQrGDloYC0mg6C6TtLhVqqxiiYQFDi4aPRxu9iBRcD4dloIZiEBXXn0DAVWmEj2n7rsORyGxbWbEnhyAkyKSu1pfzVUAPZqpXnfRKTqW2rI/9GG4cG0i7B5zP3uL8kT1dji0L9zWB9MMdZygOyPaqlJlHJ/OicWhKcqZYMuxh1D3o4VzYhjuaEctoEWNm8T+NhQehwL9uEEoUHwjm1pIIEul7O2T9Sn0X6+A5+qpUPPKwFd3M4O1QNkGbdNxZxBy4Kd5WfdsVveOQIM4YIHdQ97xbtigFLNVSjdwaUiI2YCuyGWPNyQGP0ak3qxlVqVC4yM5Wo7NPefPXwGi/dyGyTzKdD+4Z4+9vLMgKVXOIZCiUDHZBbEtHEs5Rf33O8WRKvwz3WxsT6FJz+2YfnTCCBv6NFqvduYyE9T1E3RxZR97EA5Vw+B53VHvvhakjTTlXIwIAES81oV489Wz6nbtER4QRuJK89vs4Gn8l9tQ8K48p3vM3ezbUcaek7/fLF2zca+P7Riys0mHMPie5gmBlsM5t7In9eYhv4sQpKvFRoL/NbP29npdeO0ev4QV0mH1OJTWogcDeTnLiIcHYaCpynT5cC8Qfq73PAy1D/Y6AGMjI2iSkWdm7+qQ="
 
 cache:
@@ -11,31 +13,48 @@ cache:
     - $HOME/.cache/pip
     - $HOME/.ccache
 
-install:
-    - pip install .
-    - pip install -r requirements-dev.txt
-
 matrix:
   fast_finish: true
   include:
-    - python: 3.6
     - python: 3.7
-      env: BUILD_DOCS=1
+      env: BUILD_DOCS=true SUBMIT_CODECOV=true NUMPY=1.17
     - python: nightly
   allow_failures:
     - python: nightly
 
+python:
+  - 3.6
+  - 3.7
+
+env:
+  - NUMPY=1.15
+  - NUMPY=1.16
+  - NUMPY=1.17
+
+install:
+  - export GIT_FULL_HASH=`git rev-parse HEAD`
+  - conda create -n testenv python=$TRAVIS_PYTHON_VERSION numpy=$NUMPY
+  - conda activate testenv
+  - conda install xraylib  # this is the only package not available on PyPI
+  - pip install -r requirements.txt
+  - pip install -r requirements-dev.txt
+  - pip install numpy==$NUMPY
+  - pip install codecov
+  - pip install .
+  - conda list
+  - pip list
+
 script:
 - flake8
+- coverage run run_tests.py
+- coverage report -m
 - |
-  if [ $RUN_VALIDATION == 'true' ]; then
-    coverage run run_tests.py
-    coverage report -m
-  fi
-- |
-  if [ $RUN_VALIDATION == 'true' AND $BUILD_DOCS ]; then
+  set -e  # If any of the following steps fail, just stop at that point.
+  if [ $BUILD_DOCS == 'true' ]; then
     pip install -r requirements-docs.txt
-    set -e  # If any of the following steps fail, just stop at that point.
     make -C docs html  # Build the documentation.
     doctr deploy --built-docs docs/_build/html .  # Publish the documentation.
   fi
+
+after_success:
+  - if [ $SUBMIT_CODECOV == 'true' ]; then codecov; fi;
